### ISSUE TITLE
Bootstrapの読み込みはマニフェストファイルに記述しよう

### ISSUE THREAD

**Issue by norotime** [K0H205/second_app#3]
https://github.com/K0H205/second_app/blob/d53c9b0fbe0d2d0377b882cb71e8a4900d5e61b7/app/assets/stylesheets/custom.scss#L1

@K0H205 ちょっとトリッキーなことをしていらっしゃいますね。

**Comment by K0H205** [comment]
まとめてcloseしようとおもったらできませんでした！次からは一つずつ潰していきます！
